export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const INITIALIZED = 'INITIALIZED';
export const ROOT_CHANGED = 'ROOT_CHANGED';
export const PERSIST_REQUEST = 'PERSIST_REQUEST';

export const FETCHING_SESSION_DATA = 'FETCHING_SESSION_DATA';
export const FETCHING_SESSION_DATA_SUCCESS = 'FETCHING_SESSION_DATA_SUCCESS';
export const FETCHING_SESSION_DATA_FAIL = 'FETCHING_SESSION_DATA_FAIL';

export const FETCHING_ATTENDEE_DATA = 'FETCHING_ATTENDEE_DATA';
export const FETCHING_ATTENDEE_DATA_SUCCESS = 'FETCHING_ATTENDEE_DATA_SUCCESS';
export const FETCHING_ATTENDEE_DATA_FAIL = 'FETCHING_ATTENDEE_DATA_FAIL';
export const SORT_USERS = 'SORT_USERS';
export const SEARCH = 'SEARCH';
export const SWIPE_RIGHT = 'SWIPE_RIGHT';
export const MY_INFO = 'MY_INFO';
